.include "src/config/config.inc"


;defines
.define maxNumberOopObjs	48
;.define oopArrayLength 9
.define oopStackTst	$aa55
.define maxExecTime 10	;number of frames oop handler may spend on a single obj before nmi watchdog throws error

;obj return codes
.ENUM 0	export
OBJR_noErr	db
OBJR_kill	db
.ende

;zp-vars,just a reference
.enum 0
  iterator INSTANCEOF iteratorStruct
zpLen ds 0
.ende

;oop structures
.STRUCT oopStackObj
flags		db	;@see OBJECT.FLAGS
id			db	;class id
num			dw	;number of core.object.create calls at obj instanciation time. used for fingerprint
;pntr		ds 3	;24bit pointer to obj in rom. needed? may be removed
void		dw
properties	dw
dp			dw	;absolute direct page adress on object variable buffer
init		dw	;obj init subroutine absolute adress
play		dw	;obj play subroutine absolute adress
kill		dw	;obj terminate subroutine absolute adress
.ENDST

.def oopStackObj.length _sizeof_oopStackObj
.export oopStackObj.length

;changing the enum below means you'll also have to modfiy the macro that generates objects
.ENUM 0	export
OOPR.flags	db	;bit0: singleton
OOPR.id			dw	;generated by saving number of class macro calls here
OOPR.zpLen	db	;length of required zeropage-buffer
OOPR.properties dw	;property flags
OOPR.rCount	db	;number of routines
OOPR.nClass	db	;relative adress of obj class name
OOPR.rInit	dw	;adress of obj init routine
OOPR.nInit	db	;relative adress of obj init routine name
OOPR.rPlay	dw 	;adress of obj play routine
OOPR.nPlay	db	;relative adress of obj play routine name
OOPR.rKill	dw 	;adress of obj terminate routine
OOPR.nKill	db	;relative adress of obj terminate routine name
OOPR.rAdd		dw 	;adress of obj additional routine
OOPR.nAdd		db	;relative adress of obj additional routine name
.ENDE

.enum 0
Hash INSTANCEOF oopObjHash
.ende

;ram buffers
.ramsection "oop ram" bank 0 slot 1
OopStack INSTANCEOF oopStackObj maxNumberOopObjs
OopStackEnd ds 0
.ends

;ram buffers
.ramsection "global oop vars" bank 0 slot 1
GLOBAL.currentObject	dw	;class number of current (last processed) object
GLOBAL.currentMethod	dw	;number of current (last called) method
GLOBAL.currentClass		dw	;class number of current (last called) method

GLOBAL.currentObjectStr		ds 3
GLOBAL.currentMethodStr			ds 3
GLOBAL.currentClassStr		ds 3
GLOBAL.garbagePresent	dw
GLOBAL.execFrame		dw
.ends



.ramsection "oop obj ram zp" bank 0 slot 2
OopObjRam ds $1800
OopObjRamEnd ds 0
.ends

;spit out globally unique obj-ids
.enum 0 export
OBJID.abstract.Iterator db
OBJID.abstract.Sort db
OBJID.abstract.Sprite db
OBJID.abstract.Background db
OBJID.abstract.Hdma db
OBJID.abstract.Script db
OBJID.abstract.Palette db
OBJID.Spc	db
OBJID.Script	db
OBJID.Msu1	db
OBJID.Msu1.audio	db
OBJID.Unit_test db
OBJID.Test_object db
OBJID.Iterator_test db
OBJID.Background.framebuffer db
OBJID.VideoMask db
OBJID.Background.generic db
OBJID.Brightness db
OBJID.Background.textlayer.8x8 db
OBJID.Background.textlayer.16x16 db
OBJID.Sprite.super db
OBJID.Palette.rotate db
MAXOBJID	ds 0
.ende


.base BSL
.bank 0 slot 0

;interfaces
.include "src/object/default/default.interface"
.include "src/object/dimension/dimension.interface"

.section "oop-class lut" superfree
OopClassLut:
	PTRLONG OopClassLut abstract.Iterator.CLS
	PTRLONG OopClassLut abstract.Sort.CLS
	PTRLONG OopClassLut abstract.Sprite.CLS
	PTRLONG OopClassLut abstract.Background.CLS
	PTRLONG OopClassLut abstract.Hdma.CLS
	PTRLONG OopClassLut abstract.Script.CLS
	PTRLONG OopClassLut abstract.Palette.CLS
	PTRLONG OopClassLut Spc.CLS
	PTRLONG OopClassLut Script.CLS
	PTRLONG OopClassLut Msu1.CLS
	PTRLONG OopClassLut Msu1.audio.CLS
	PTRLONG OopClassLut Unit_test.CLS
	PTRLONG OopClassLut Test_object.CLS
	PTRLONG OopClassLut Iterator_test.CLS
	PTRLONG OopClassLut Background.framebuffer.CLS
	PTRLONG OopClassLut VideoMask.CLS
	PTRLONG OopClassLut Background.generic.CLS
	PTRLONG OopClassLut Brightness.CLS
	PTRLONG OopClassLut Background.textlayer.8x8.CLS
	PTRLONG OopClassLut Background.textlayer.16x16.CLS
	PTRLONG OopClassLut Sprite.super.CLS
	PTRLONG OopClassLut Palette.rotate.CLS
.ends
